FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye

# Install step
RUN wget https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.deb \
&& sudo dpkg -i step-cli_amd64.deb